### ISSUE TITLE
在contenView上面加一个简单的tableView,点击一下tableView,上面数据就消失,点击tableViewCell也没有任何反应,请问是咋回事

### ISSUE THREAD

**Issue by ScofieldTang** [heartjoy/CQSideBarManager#3]
如题,可以写个demo看下

**Comment by heartjoy** [comment]
你好，能把你写的代码贴出来吗？从问题描述上面看，不好找原因

**Comment by ScofieldTang** [comment]
您好 下面是我的代码 您看下 我试了在您的demo上添加界面也不行 
`#pragma mark - 点击筛选
- (void)shaixuanAction{
    [[CQSideBarManager sharedInstance] openSideBar:self];
}
#pragma mark - 筛选视图
- (UIView *)viewForSideBar{
    WYSideBarVC *sidevc = [WYSideBarVC new];
    sidevc.view.width = ScreenWidth - 35;
    return sidevc.view;
}`

WYSideBarVC中添加一个button,点击button 没有走响应事件
` UIButton *doneBtn = [UIButton buttonWithType:UIButtonTypeSystem];
    doneBtn.frame = CGRectMake(resetBtn.right, resetBtn.y, resetBtn.width, resetBtn.height);
    [doneBtn setTitle:@"完成" forState:UIControlStateNormal];
    [doneBtn setBackgroundColor:kRGBA(204, 177, 140)];
    [doneBtn setTintColor:[UIColor whiteColor]];
    doneBtn.titleLabel.font = kFont(18);
    [doneBtn addTarget:self action:@selector(doneAction) forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:doneBtn];`

下面的这个触发方法不走,您看下
`#pragma mark - 完成
- (void)doneAction{
    DLog(@"完成");
    [[CQSideBarManager sharedInstance] closeSideBar];
}`

或者方便加个QQ详谈一下吗?我的QQ是643759142

**Comment by heartjoy** [comment]
前段时间比较忙，没来得及回复，我已经发布了release v0.1.2，对反馈的问题已作出解释，请查看
