### ISSUE TITLE
如果在侧边栏上再打开一个侧边栏，怎么管理第二个，

### ISSUE THREAD

**Issue by Mandyhold** [heartjoy/CQSideBarManager#5]
[[CQSideBarManager sharedInstance] closeSideBar];

**Comment by Mandyhold** [comment]
如果在侧边栏上再打开一个侧边栏，怎么管理第二个，在第二个侧边栏使用[[CQSideBarManager sharedInstance] closeSideBar];会把所有第一个侧边栏contentView释放掉～～～～～

**Comment by heartjoy** [comment]
目前不支持管理多个，单例只维护了一个侧边栏
